import sys
from tkinter import *
from tkinter import ttk

tb=Tk()
tb.title("toetsenbord")
tb.geometry("1366x768")
tb.configure(background="black")

nums=Frame(tb, bg='black')
nums.place(relx=0.8, rely=0.15, relwidth=0.2, relheight=0.5)
brt = 0.0666
hct = 0.2
ta=0.09
r1=0
r2=0.2
r3=0.4
r4=0.6
r5=0.8

sl=Button(nums,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='/')
sl.place(relx=0.25,rely=0,relwidth=0.25,relheight=0.2)
ml=Button(nums,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='*')
ml.place(relx=0.50,rely=0,relwidth=0.25,relheight=0.2)
mn=Button(nums,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='-')
mn.place(relx=0.75,rely=0,relwidth=0.25,relheight=0.2)
ps=Button(nums,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='+')
ps.place(relx=0.75,rely=0.2,relwidth=0.25,relheight=0.4)
sev=Button(nums,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='7')
sev.place(relx=0,rely=0.2,relwidth=0.25,relheight=0.2)
at=Button(nums,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='8')
at.place(relx=0.25,rely=0.2,relwidth=0.25,relheight=0.2)
nuf=Button(nums,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='9')
nuf.place(relx=0.5,rely=0.2,relwidth=0.25,relheight=0.2)
vr=Button(nums,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='4')
vr.place(relx=0,rely=0.4,relwidth=0.25,relheight=0.2)
nf=Button(nums,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='5')
nf.place(relx=0.25,rely=0.4,relwidth=0.25,relheight=0.2)
zs=Button(nums,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='6')
zs.place(relx=0.50,rely=0.4,relwidth=0.25,relheight=0.2)
een=Button(nums,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='1')
een.place(relx=0,rely=0.6,relwidth=0.25,relheight=0.2)
tw=Button(nums,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='2')
tw.place(relx=0.25,rely=0.6,relwidth=0.25,relheight=0.2)
dr=Button(nums,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='3')
dr.place(relx=0.5,rely=0.6,relwidth=0.25,relheight=0.2)
ntr=Button(nums,bg='black',fg='white',bd=0,font=("gill sans MT",15),text='Enter')
ntr.place(relx=0.75,rely=0.6,relwidth=0.25,relheight=0.4)
nul=Button(nums,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='0')
nul.place(relx=0,rely=0.8,relwidth=0.50,relheight=0.2)
pnt=Button(nums,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='.')
pnt.place(relx=0.5,rely=0.8,relwidth=0.25,relheight=0.2)
def so():
    mkb=Frame(tb, bg='black')
    mkb.place(relx=0., rely=0.4, relwidth=0.8, relheight=0.5)

    brt = 0.0666
    hct = 0.2
    ta=0.09
    r1=0
    r2=0.2
    r3=0.4
    r4=0.6
    r5=0.8

    mt=Button(mkb,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='²')
    mt.place(relx=0,rely=r1,relwidth=brt,relheight=hct)
    mt=Button(mkb,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='&')
    mt.place(relx=brt*1,rely=r1,relwidth=brt,relheight=hct)
    mt=Button(mkb,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='é')
    mt.place(relx=brt*2,rely=r1,relwidth=brt,relheight=hct)
    mt=Button(mkb,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='"')
    mt.place(relx=brt*3,rely=r1,relwidth=brt,relheight=hct)
    mt=Button(mkb,bg='black',fg='white',bd=0,font=("gill sans MT",20),text="'")
    mt.place(relx=brt*4,rely=r1,relwidth=brt,relheight=hct)
    mt=Button(mkb,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='(')
    mt.place(relx=brt*5,rely=r1,relwidth=brt,relheight=hct)
    mt=Button(mkb,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='§')
    mt.place(relx=brt*6,rely=r1,relwidth=brt,relheight=hct)
    mt=Button(mkb,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='è')
    mt.place(relx=brt*7,rely=r1,relwidth=brt,relheight=hct)
    mt=Button(mkb,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='!')
    mt.place(relx=brt*8,rely=r1,relwidth=brt,relheight=hct)
    mt=Button(mkb,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='ç')
    mt.place(relx=brt*9,rely=r1,relwidth=brt,relheight=hct)
    mt=Button(mkb,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='à')
    mt.place(relx=brt*10,rely=r1,relwidth=brt,relheight=hct)
    mt=Button(mkb,bg='black',fg='white',bd=0,font=("gill sans MT",20),text=')')
    mt.place(relx=brt*11,rely=r1,relwidth=brt,relheight=hct)
    mt=Button(mkb,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='-')
    mt.place(relx=brt*12,rely=r1,relwidth=brt,relheight=hct)
    mt=Button(mkb,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='<--')
    mt.place(relx=brt*13,rely=r1,relwidth=brt*2+0.001,relheight=hct)

    mt=Button(mkb,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='Tab')
    mt.place(relx=0,rely=r2,relwidth=ta,relheight=hct)
    mt=Button(mkb,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='a')
    mt.place(relx=ta,rely=r2,relwidth=brt,relheight=hct)
    mt=Button(mkb,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='z')
    mt.place(relx=ta+brt,rely=r2,relwidth=brt,relheight=hct)
    mt=Button(mkb,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='e')
    mt.place(relx=ta+brt*2,rely=r2,relwidth=brt,relheight=hct)
    mt=Button(mkb,bg='black',fg='white',bd=0,font=("gill sans MT",20),text="r")
    mt.place(relx=ta+brt*3,rely=r2,relwidth=brt,relheight=hct)
    mt=Button(mkb,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='t')
    mt.place(relx=ta+brt*4,rely=r2,relwidth=brt,relheight=hct)
    mt=Button(mkb,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='y')
    mt.place(relx=ta+brt*5,rely=r2,relwidth=brt,relheight=hct)
    mt=Button(mkb,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='u')
    mt.place(relx=ta+brt*6,rely=r2,relwidth=brt,relheight=hct)
    mt=Button(mkb,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='i')
    mt.place(relx=ta+brt*7,rely=r2,relwidth=brt,relheight=hct)
    mt=Button(mkb,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='o')
    mt.place(relx=ta+brt*8,rely=r2,relwidth=brt,relheight=hct)
    mt=Button(mkb,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='p')
    mt.place(relx=ta+brt*9,rely=r2,relwidth=brt,relheight=hct)
    mt=Button(mkb,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='^')
    mt.place(relx=ta+brt*10,rely=r2,relwidth=brt,relheight=hct)
    mt=Button(mkb,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='$')
    mt.place(relx=ta+brt*11,rely=r2,relwidth=brt,relheight=hct)
    mt=Button(mkb,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='Enter')
    mt.place(relx=ta+brt*12,rely=r2,relwidth=0.11+0.001,relheight=hct)

    ta=0.1

    mt=Button(mkb,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='C Lock')
    mt.place(relx=0,rely=r3,relwidth=ta,relheight=hct)
    mt=Button(mkb,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='q')
    mt.place(relx=ta,rely=r3,relwidth=brt,relheight=hct)
    mt=Button(mkb,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='s')
    mt.place(relx=ta+brt,rely=r3,relwidth=brt,relheight=hct)
    mt=Button(mkb,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='d')
    mt.place(relx=ta+brt*2,rely=r3,relwidth=brt,relheight=hct)
    mt=Button(mkb,bg='black',fg='white',bd=0,font=("gill sans MT",20),text="f")
    mt.place(relx=ta+brt*3,rely=r3,relwidth=brt,relheight=hct)
    mt=Button(mkb,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='g')
    mt.place(relx=ta+brt*4,rely=r3,relwidth=brt,relheight=hct)
    mt=Button(mkb,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='h')
    mt.place(relx=ta+brt*5,rely=r3,relwidth=brt,relheight=hct)
    mt=Button(mkb,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='j')
    mt.place(relx=ta+brt*6,rely=r3,relwidth=brt,relheight=hct)
    mt=Button(mkb,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='k')
    mt.place(relx=ta+brt*7,rely=r3,relwidth=brt,relheight=hct)
    mt=Button(mkb,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='l')
    mt.place(relx=ta+brt*8,rely=r3,relwidth=brt,relheight=hct)
    mt=Button(mkb,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='m')
    mt.place(relx=ta+brt*9,rely=r3,relwidth=brt,relheight=hct)
    mt=Button(mkb,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='ù')
    mt.place(relx=ta+brt*10,rely=r3,relwidth=brt,relheight=hct)
    mt=Button(mkb,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='µ')
    mt.place(relx=ta+brt*11,rely=r3,relwidth=brt,relheight=hct)
    mt=Button(mkb,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='Enter')
    mt.place(relx=ta+brt*12,rely=r3,relwidth=0.1+0.001,relheight=hct)

    ta=0.08

    mt=Button(mkb,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='Shift')
    mt.place(relx=0,rely=r4,relwidth=ta,relheight=hct)
    mt=Button(mkb,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='<')
    mt.place(relx=ta,rely=r4,relwidth=brt,relheight=hct)
    mt=Button(mkb,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='w')
    mt.place(relx=ta+brt,rely=r4,relwidth=brt,relheight=hct)
    mt=Button(mkb,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='x')
    mt.place(relx=ta+brt*2,rely=r4,relwidth=brt,relheight=hct)
    mt=Button(mkb,bg='black',fg='white',bd=0,font=("gill sans MT",20),text="c")
    mt.place(relx=ta+brt*3,rely=r4,relwidth=brt,relheight=hct)
    mt=Button(mkb,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='v')
    mt.place(relx=ta+brt*4,rely=r4,relwidth=brt,relheight=hct)
    mt=Button(mkb,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='b')
    mt.place(relx=ta+brt*5,rely=r4,relwidth=brt,relheight=hct)
    mt=Button(mkb,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='n')
    mt.place(relx=ta+brt*6,rely=r4,relwidth=brt,relheight=hct)
    mt=Button(mkb,bg='black',fg='white',bd=0,font=("gill sans MT",20),text=',')
    mt.place(relx=ta+brt*7,rely=r4,relwidth=brt,relheight=hct)
    mt=Button(mkb,bg='black',fg='white',bd=0,font=("gill sans MT",20),text=';')
    mt.place(relx=ta+brt*8,rely=r4,relwidth=brt,relheight=hct)
    mt=Button(mkb,bg='black',fg='white',bd=0,font=("gill sans MT",20),text=':')
    mt.place(relx=ta+brt*9,rely=r4,relwidth=brt,relheight=hct)
    mt=Button(mkb,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='=')
    mt.place(relx=ta+brt*10,rely=r4,relwidth=brt,relheight=hct)
    mt=Button(mkb,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='Shift')
    mt.place(relx=ta+brt*11,rely=r4,relwidth=0.187,relheight=hct)

    mt=Button(mkb,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='Crtl')
    mt.place(relx=0,rely=r5,relwidth=0.09,relheight=hct)
    mt=Button(mkb,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='Home')
    mt.place(relx=0.09,rely=r5,relwidth=0.09,relheight=hct)
    mt=Button(mkb,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='Alt')
    mt.place(relx=0.18,rely=r5,relwidth=0.08,relheight=hct)
    mt=Button(mkb,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='')
    mt.place(relx=0.26,rely=r5,relwidth=0.38,relheight=hct)
    mt=Button(mkb,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='Alt Gr')
    mt.place(relx=0.64,rely=r5,relwidth=0.09,relheight=hct)
    mt=Button(mkb,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='Home')
    mt.place(relx=0.73,rely=r5,relwidth=0.09,relheight=hct)
    mt=Button(mkb,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='Menu')
    mt.place(relx=0.82,rely=r5,relwidth=0.09,relheight=hct)
    mt=Button(mkb,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='Crtl')
    mt.place(relx=0.91,rely=r5,relwidth=0.09,relheight=hct)

fs=Frame(tb, bg='black')
fs.place(relx=0., rely=0.25, relwidth=0.8, relheight=0.1)

mt=Button(fs,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='Esc')
mt.place(relx=0,rely=0,relwidth=brt,relheight=1)
mt=Button(fs,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='F1')
mt.place(relx=brt*1,rely=0,relwidth=brt,relheight=1)
mt=Button(fs,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='F2')
mt.place(relx=brt*2,rely=0,relwidth=brt,relheight=1)
mt=Button(fs,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='F3')
mt.place(relx=brt*3,rely=0,relwidth=brt,relheight=1)
mt=Button(fs,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='F4')
mt.place(relx=brt*4,rely=0,relwidth=brt,relheight=1)
mt=Button(fs,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='F5')
mt.place(relx=brt*5,rely=0,relwidth=brt,relheight=1)
mt=Button(fs,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='F6')
mt.place(relx=brt*6,rely=0,relwidth=brt,relheight=1)
mt=Button(fs,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='F7')
mt.place(relx=brt*7,rely=0,relwidth=brt,relheight=1)
mt=Button(fs,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='F8')
mt.place(relx=brt*8,rely=0,relwidth=brt,relheight=1)
mt=Button(fs,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='F9')
mt.place(relx=brt*9,rely=0,relwidth=brt,relheight=1)
mt=Button(fs,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='F10')
mt.place(relx=brt*10,rely=0,relwidth=brt,relheight=1)
mt=Button(fs,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='F11')
mt.place(relx=brt*11,rely=0,relwidth=brt,relheight=1)
mt=Button(fs,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='F12')
mt.place(relx=brt*12,rely=0,relwidth=brt,relheight=1)
mt=Button(fs,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='Del')
mt.place(relx=brt*13,rely=0,relwidth=brt,relheight=1)
mt=Button(fs,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='Ins')
mt.place(relx=brt*14,rely=0,relwidth=brt+0.001,relheight=1)

ar=Frame(tb, bg='blue')
ar.place(relx=0.8, rely=0.7, relwidth=0.2, relheight=0.2)

nl=Button(ar,bg='black',fg='white',bd=0,font=("gill sans MT",15),text='Home')
nl.place(relx=0,rely=0,relwidth=0.25,relheight=0.5)
sl=Button(ar,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='Up')
sl.place(relx=0.25,rely=0,relwidth=0.25,relheight=0.5)
ml=Button(ar,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='End')
ml.place(relx=0.50,rely=0,relwidth=0.25,relheight=0.5)
mn=Button(ar,bg='black',fg='white',bd=0,font=("gill sans MT",15),text='Pg Up')
mn.place(relx=0.75,rely=0,relwidth=0.25,relheight=0.5)
ps=Button(ar,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='Dn')
ps.place(relx=0.25,rely=0.5,relwidth=0.25,relheight=0.5)
sev=Button(ar,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='->')
sev.place(relx=0.5,rely=0.5,relwidth=0.25,relheight=0.5)
at=Button(ar,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='<-')
at.place(relx=0,rely=0.5,relwidth=0.25,relheight=0.5)
at=Button(ar,bg='black',fg='white',bd=0,font=("gill sans MT",15),text='Pg Dn')
at.place(relx=0.75,rely=0.5,relwidth=0.25,relheight=0.5)

def si():
    sft=Frame(tb, bg='black')
    sft.place(relx=0., rely=0.4, relwidth=0.8, relheight=0.5)

    brt = 0.0666
    hct = 0.2
    ta=0.09
    r1=0
    r2=0.2
    r3=0.4
    r4=0.6
    r5=0.8

    mt=Button(sft,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='³')
    mt.place(relx=0,rely=r1,relwidth=brt,relheight=hct)
    mt=Button(sft,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='1')
    mt.place(relx=brt*1,rely=r1,relwidth=brt,relheight=hct)
    mt=Button(sft,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='2')
    mt.place(relx=brt*2,rely=r1,relwidth=brt,relheight=hct)
    mt=Button(sft,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='3')
    mt.place(relx=brt*3,rely=r1,relwidth=brt,relheight=hct)
    mt=Button(sft,bg='black',fg='white',bd=0,font=("gill sans MT",20),text="4")
    mt.place(relx=brt*4,rely=r1,relwidth=brt,relheight=hct)
    mt=Button(sft,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='5')
    mt.place(relx=brt*5,rely=r1,relwidth=brt,relheight=hct)
    mt=Button(sft,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='6')
    mt.place(relx=brt*6,rely=r1,relwidth=brt,relheight=hct)
    mt=Button(sft,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='7')
    mt.place(relx=brt*7,rely=r1,relwidth=brt,relheight=hct)
    mt=Button(sft,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='8')
    mt.place(relx=brt*8,rely=r1,relwidth=brt,relheight=hct)
    mt=Button(sft,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='9')
    mt.place(relx=brt*9,rely=r1,relwidth=brt,relheight=hct)
    mt=Button(sft,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='0')
    mt.place(relx=brt*10,rely=r1,relwidth=brt,relheight=hct)
    mt=Button(sft,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='°')
    mt.place(relx=brt*11,rely=r1,relwidth=brt,relheight=hct)
    mt=Button(sft,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='_')
    mt.place(relx=brt*12,rely=r1,relwidth=brt,relheight=hct)
    mt=Button(sft,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='<--')
    mt.place(relx=brt*13,rely=r1,relwidth=brt*2+0.001,relheight=hct)

    mt=Button(sft,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='Tab')
    mt.place(relx=0,rely=r2,relwidth=ta,relheight=hct)
    mt=Button(sft,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='A')
    mt.place(relx=ta,rely=r2,relwidth=brt,relheight=hct)
    mt=Button(sft,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='Z')
    mt.place(relx=ta+brt,rely=r2,relwidth=brt,relheight=hct)
    mt=Button(sft,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='E')
    mt.place(relx=ta+brt*2,rely=r2,relwidth=brt,relheight=hct)
    mt=Button(sft,bg='black',fg='white',bd=0,font=("gill sans MT",20),text="R")
    mt.place(relx=ta+brt*3,rely=r2,relwidth=brt,relheight=hct)
    mt=Button(sft,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='T')
    mt.place(relx=ta+brt*4,rely=r2,relwidth=brt,relheight=hct)
    mt=Button(sft,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='Y')
    mt.place(relx=ta+brt*5,rely=r2,relwidth=brt,relheight=hct)
    mt=Button(sft,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='U')
    mt.place(relx=ta+brt*6,rely=r2,relwidth=brt,relheight=hct)
    mt=Button(sft,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='I')
    mt.place(relx=ta+brt*7,rely=r2,relwidth=brt,relheight=hct)
    mt=Button(sft,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='O')
    mt.place(relx=ta+brt*8,rely=r2,relwidth=brt,relheight=hct)
    mt=Button(sft,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='P')
    mt.place(relx=ta+brt*9,rely=r2,relwidth=brt,relheight=hct)
    mt=Button(sft,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='"')
    mt.place(relx=ta+brt*10,rely=r2,relwidth=brt,relheight=hct)
    mt=Button(sft,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='*')
    mt.place(relx=ta+brt*11,rely=r2,relwidth=brt,relheight=hct)
    mt=Button(sft,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='Enter')
    mt.place(relx=ta+brt*12,rely=r2,relwidth=0.11+0.001,relheight=hct)

    ta=0.1

    mt=Button(sft,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='C Lock')
    mt.place(relx=0,rely=r3,relwidth=ta,relheight=hct)
    mt=Button(sft,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='Q')
    mt.place(relx=ta,rely=r3,relwidth=brt,relheight=hct)
    mt=Button(sft,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='S')
    mt.place(relx=ta+brt,rely=r3,relwidth=brt,relheight=hct)
    mt=Button(sft,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='D')
    mt.place(relx=ta+brt*2,rely=r3,relwidth=brt,relheight=hct)
    mt=Button(sft,bg='black',fg='white',bd=0,font=("gill sans MT",20),text="F")
    mt.place(relx=ta+brt*3,rely=r3,relwidth=brt,relheight=hct)
    mt=Button(sft,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='G')
    mt.place(relx=ta+brt*4,rely=r3,relwidth=brt,relheight=hct)
    mt=Button(sft,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='H')
    mt.place(relx=ta+brt*5,rely=r3,relwidth=brt,relheight=hct)
    mt=Button(sft,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='J')
    mt.place(relx=ta+brt*6,rely=r3,relwidth=brt,relheight=hct)
    mt=Button(sft,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='K')
    mt.place(relx=ta+brt*7,rely=r3,relwidth=brt,relheight=hct)
    mt=Button(sft,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='L')
    mt.place(relx=ta+brt*8,rely=r3,relwidth=brt,relheight=hct)
    mt=Button(sft,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='M')
    mt.place(relx=ta+brt*9,rely=r3,relwidth=brt,relheight=hct)
    mt=Button(sft,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='%')
    mt.place(relx=ta+brt*10,rely=r3,relwidth=brt,relheight=hct)
    mt=Button(sft,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='£')
    mt.place(relx=ta+brt*11,rely=r3,relwidth=brt,relheight=hct)
    mt=Button(sft,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='Enter')
    mt.place(relx=ta+brt*12,rely=r3,relwidth=0.1+0.001,relheight=hct)

    ta=0.08

    mt=Button(sft,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='Shift')
    mt.place(relx=0,rely=r4,relwidth=ta,relheight=hct)
    mt=Button(sft,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='>')
    mt.place(relx=ta,rely=r4,relwidth=brt,relheight=hct)
    mt=Button(sft,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='W')
    mt.place(relx=ta+brt,rely=r4,relwidth=brt,relheight=hct)
    mt=Button(sft,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='X')
    mt.place(relx=ta+brt*2,rely=r4,relwidth=brt,relheight=hct)
    mt=Button(sft,bg='black',fg='white',bd=0,font=("gill sans MT",20),text="C")
    mt.place(relx=ta+brt*3,rely=r4,relwidth=brt,relheight=hct)
    mt=Button(sft,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='V')
    mt.place(relx=ta+brt*4,rely=r4,relwidth=brt,relheight=hct)
    mt=Button(sft,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='B')
    mt.place(relx=ta+brt*5,rely=r4,relwidth=brt,relheight=hct)
    mt=Button(sft,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='N')
    mt.place(relx=ta+brt*6,rely=r4,relwidth=brt,relheight=hct)
    mt=Button(sft,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='?')
    mt.place(relx=ta+brt*7,rely=r4,relwidth=brt,relheight=hct)
    mt=Button(sft,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='.')
    mt.place(relx=ta+brt*8,rely=r4,relwidth=brt,relheight=hct)
    mt=Button(sft,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='/')
    mt.place(relx=ta+brt*9,rely=r4,relwidth=brt,relheight=hct)
    mt=Button(sft,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='+')
    mt.place(relx=ta+brt*10,rely=r4,relwidth=brt,relheight=hct)
    mt=Button(sft,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='Shift')
    mt.place(relx=ta+brt*11,rely=r4,relwidth=0.187,relheight=hct)

    mt=Button(mkb,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='Crtl')
    mt.place(relx=0,rely=r5,relwidth=0.09,relheight=hct)
    mt=Button(mkb,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='Home')
    mt.place(relx=0.09,rely=r5,relwidth=0.09,relheight=hct)
    mt=Button(mkb,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='Alt')
    mt.place(relx=0.18,rely=r5,relwidth=0.08,relheight=hct)
    mt=Button(mkb,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='')
    mt.place(relx=0.26,rely=r5,relwidth=0.38,relheight=hct)
    mt=Button(mkb,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='Alt Gr')
    mt.place(relx=0.64,rely=r5,relwidth=0.09,relheight=hct)
    mt=Button(mkb,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='Home')
    mt.place(relx=0.73,rely=r5,relwidth=0.09,relheight=hct)
    mt=Button(mkb,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='Menu')
    mt.place(relx=0.82,rely=r5,relwidth=0.09,relheight=hct)
    mt=Button(mkb,bg='black',fg='white',bd=0,font=("gill sans MT",20),text='Crtl')
    mt.place(relx=0.91,rely=r5,relwidth=0.09,relheight=hct)


tb.mainloop()